from . import start
from . import back
from . import menu
from . import shop
from . import course
from . import register
from . import settings
from . import contact
from . import channel
from . import send_video_to_admin
from . import send_photo_to_admin
from . import send_file_to_admin
from . import send_voice_to_admin
